[package]
name = "ruxture"
version = "0.1.0"
authors = ["Par Winzell <zell@fb.com>"]
edition = "2018"

[dependencies]
clap = "2"
byteordered = "0"
simple-error = "0"
enum-primitive-derive = "^0.1"
num-traits = "^0.1"
lazy_static = "^1.3"